#exceptions using try...except
# try:
#     numerator=10
#     denominator=0
#     result=numerator/denominator
#     print(result)
# except:
#     print("error:denominator cannot be zero")

# try:
#     even_numbers=[2,6,6,8]
#     print(even_numbers[5])
# except ZeroDivisionError:
#     print("denominator cannot be zero")
# except IndexError:
#     print("index out of bound")

# try:
#     num=int(input("enter a number:"))
#     assert num%2==0
# except:
#     print("not even number!")
# else:
#     reciporcal=1/num
#     print(reciporcal)

#python...try finally
# try:
#     numerator=10
#     denominator=0
#     result=numerator/denominator
#     print(result)
# except:
#     print("error:denominator cannot be zero")
# finally:
#     print("this is finally block.")


